namespace OTRMod.ID;

internal class Text {
	public enum Codes : byte {
		END = 0x02, BOX_BREAK = 0x04,
		COLOR, SHIFT, TEXTID,
		QUICKTEXT_ENABLE, QUICKTEXT_DISABLE,
		PERSISTENT, // LF (\n)
		EVENT,
		BOX_BREAK_DELAYED, AWAIT_BUTTON_PRESS,
		FADE, NAME, OCARINA,
		FADE2, SFX, ITEM_ICON,
		TEXT_SPEED, BACKGROUND,
		MARATHON_TIME, RACE_TIME,
		POINTS, TOKENS,
		UNSKIPPABLE,
		TWO_CHOICE, THREE_CHOICE,
		FISH_INFO, HIGHSCORE, TIME
	}

	public enum Color {
		DEFAULT = 0x40,
		RED, ADJUSTABLE,
		BLUE, LIGHTBLUE,
		PURPLE, YELLOW,
		BLACK
	}

	public enum Highscores {
		HS_HORSE_ARCHERY, HS_POE_POINTS, HS_LARGEST_FISH,
		HS_HORSE_RACE, HS_MARATHON, HS_DAMPE_RACE = 0x06
	}
}
