namespace OTRMod.ID;

public static class Text {
	public enum Code : byte {
		END = 0x02, BOX_BREAK = 0x04,
		COLOR, SHIFT, TEXTID,
		QUICKTEXT_ENABLE, QUICKTEXT_DISABLE,
		PERSISTENT, // LF (\n)
		EVENT,
		BOX_BREAK_DELAYED, AWAIT_BUTTON_PRESS,
		FADE, NAME, OCARINA,
		FADE2, SFX, ITEM_ICON,
		TEXT_SPEED, BACKGROUND,
		MARATHON_TIME, RACE_TIME,
		POINTS, TOKENS,
		UNSKIPPABLE,
		TWO_CHOICE, THREE_CHOICE,
		FISH_INFO, HIGHSCORE, TIME
	}

	public enum Color {
		DEFAULT = 0x40,
		RED, ADJUSTABLE,
		BLUE, LIGHTBLUE,
		PURPLE, YELLOW,
		BLACK
	}

	public enum Highscore {
		HS_HORSE_ARCHERY, HS_POE_POINTS, HS_LARGEST_FISH,
		HS_HORSE_RACE, HS_MARATHON, HS_DAMPE_RACE = 0x06
	}

	public enum TextBoxType : byte {
		TEXTBOX_TYPE_BLACK,
		TEXTBOX_TYPE_WOODEN,
		TEXTBOX_TYPE_BLUE,
		TEXTBOX_TYPE_OCARINA,
		TEXTBOX_TYPE_NONE_BOTTOM,
		TEXTBOX_TYPE_NONE_NO_SHADOW,
		TEXTBOX_TYPE_CREDITS = 11
	}

	public enum TextBoxPosition : byte {
		TEXTBOX_POS_VARIABLE,
		TEXTBOX_POS_TOP,
		TEXTBOX_POS_MIDDLE,
		TEXTBOX_POS_BOTTOM
	}

	public class MessageEntry {
		public ushort ID;
		public TextBoxType BoxType;
		public TextBoxPosition BoxPos;
		public int Offset;
		public List<byte>? Content;
	}
}
