//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated> 
//------------------------------------------------------------------------------

namespace OTRMod.Web.Shared.Resources {
	using System;

	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by a text template.
	// To add or remove a member, edit your .ResX file.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResXResourceManager", "1.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class Resource {
	
	private static global::System.Resources.ResourceManager resourceMan;
	
	private static global::System.Globalization.CultureInfo resourceCulture;
	
	[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
	internal Resource() {
	}
	
	/// <summary>
	///   Returns the cached ResourceManager instance used by this class.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
	public static global::System.Resources.ResourceManager ResourceManager {
		get {
		if (object.ReferenceEquals(resourceMan, null)) {
			global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OTRMod.Web.Shared.Resources.Resource", typeof(Resource).Assembly);
			resourceMan = temp;
		}
		return resourceMan;
		}
	}
	
	/// <summary>
	///   Overrides the current thread's CurrentUICulture property for all
	///   resource lookups using this strongly typed resource class.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
	public static global::System.Globalization.CultureInfo Culture {
		get { return resourceCulture; } set { resourceCulture = value; }
	}

	public static string GetLocalisedString(string str) {
		return ResourceManager.GetString(str, resourceCulture) ?? str;
	}

	public static string btn_gen_otr => GetLocalisedString("btn_gen_otr");

	public static string btn_wait => GetLocalisedString("btn_wait");

	public static string dev_by => GetLocalisedString("dev_by");

	public static string error => GetLocalisedString("error");

	public static string error_404_h1 => GetLocalisedString("error_404_h1");

	public static string error_404_p => GetLocalisedString("error_404_p");

	public static string error_404_title => GetLocalisedString("error_404_title");

	public static string get_otr_h1 => GetLocalisedString("get_otr_h1");

	public static string get_otr_tab => GetLocalisedString("get_otr_tab");

	public static string get_otr_title => GetLocalisedString("get_otr_title");

	public static string gimme_cafe => GetLocalisedString("gimme_cafe");

	public static string info_fin => GetLocalisedString("info_fin");

	public static string info_not_sel => GetLocalisedString("info_not_sel");

	public static string info_sel => GetLocalisedString("info_sel");

	public static string info_wait => GetLocalisedString("info_wait");

	public static string lang_tag => GetLocalisedString("lang_tag");

	public static string nav_menu => GetLocalisedString("nav_menu");

	public static string sel_rom => GetLocalisedString("sel_rom");

	public static string sel_script => GetLocalisedString("sel_script");

	public static string upd_btn => GetLocalisedString("upd_btn");

	public static string upd_txt => GetLocalisedString("upd_txt");

	public static string visit_on_gh => GetLocalisedString("visit_on_gh");

	}
}
