//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTRMod.Web.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OTRMod.Web.Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate OTR.
        /// </summary>
        public static string btn_gen_otr {
            get {
                return ResourceManager.GetString("btn_gen_otr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get OTR mod from ROM image.
        /// </summary>
        public static string get_otr_h1 {
            get {
                return ResourceManager.GetString("get_otr_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get OTR.
        /// </summary>
        public static string get_otr_tab {
            get {
                return ResourceManager.GetString("get_otr_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTRMod Web - Get OTR.
        /// </summary>
        public static string get_otr_title {
            get {
                return ResourceManager.GetString("get_otr_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTR generated successfully!.
        /// </summary>
        public static string info_fin {
            get {
                return ResourceManager.GetString("info_fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a script file and ROM to generate the OTR..
        /// </summary>
        public static string info_not_sel {
            get {
                return ResourceManager.GetString("info_not_sel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the &quot;Generate OTR&quot; button when you&apos;re ready..
        /// </summary>
        public static string info_sel {
            get {
                return ResourceManager.GetString("info_sel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while your OTR is being generated....
        /// </summary>
        public static string info_wait {
            get {
                return ResourceManager.GetString("info_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a ROM: .
        /// </summary>
        public static string sel_rom {
            get {
                return ResourceManager.GetString("sel_rom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a script: .
        /// </summary>
        public static string sel_script {
            get {
                return ResourceManager.GetString("sel_script", resourceCulture);
            }
        }
    }
}
